# server {
#     listen 80;
#     # server_name localhost;
#     server_name 157.180.23.211;

#     root /usr/share/nginx/html;
#     index index.html;

#     location / {
#         try_files $uri $uri/ /index.html;
#     }
# }