services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./backend/pocketbase
    ports:
      - '8090:8090'
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    # volumes:
    #   - ./frontend/dist:/usr/share/nginx/html
    #   - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - pocketbase

volumes:
  pb_data:

version: '3.9'
